name: Photo contribution
description: Offer a photo for inclusion
title: "[Photo] "
labels:
  - photos
body:
  - type: input
    id: store
    attributes:
      label: Store
      description: Store name or id
    validations:
      required: true
  - type: textarea
    id: photo
    attributes:
      label: Photo link
      description: Link to the photo or explain how you will provide it
    validations:
      required: true
  - type: dropdown
    id: license
    attributes:
      label: License
      options:
        - CC-BY-4.0
        - CC0-1.0
    validations:
      required: true
  - type: checkboxes
    id: ownership
    attributes:
      label: Ownership
      options:
        - label: I took this photo myself or have the right to license it.
          required: true
