/* This file is generated by packages/data/scripts/generate-mobile-stores.mjs. */

export const localPhotosMap: Record<string, unknown> = {
  "./assets/stores/apple-champs-elysees-1.webp": require("../../../assets/stores/apple-champs-elysees-1.webp"),
  "./assets/stores/apple-champs-elysees-2.webp": require("../../../assets/stores/apple-champs-elysees-2.webp")
};
